### PR TITLE
SKY-3: Footer Design

### PR DESCRIPTION
**Pull request by anurmamedov**
design of footer via bootstrap

### CODE REVIEW

**Comment by Aymammet** [comment]
There are still a bunch of __pycashe__ files. Be sure that your gitignore works.

**Comment by Aymammet** [comment]
Before commiting you can check your changes.

**Comment by anurmamedov** [comment]
gitignore updated, i guess because your main gitignore didn't have some files in it when i was pulling it in.

**Comment by Aymammet** [comment]
> gitignore updated, i guess because your main gitignore didn't have some files in it when i was pulling it in.

It should work. Check again. Or : 
- save your changes in another file (to use them later)
-  delete all local branches
- pull main again
- open new branch
- make sure that gitignore there
- copy your changes
- push

**Pull request closed without merging**
