### PR TITLE
an/SKY-16: Profile user models created

### PR DESCRIPTION
**Pull request by anurmamedov**
Models created in Profiles app  such as email, profession and bio. 
Main/admin has been coded with Class Admin.

admin generated

### CODE REVIEW

**Review by Aymammet — CHANGES_REQUESTED** [review]
Why you removed __init__.py file in apps. They should stay there

**Comment by anurmamedov** [comment]
i removed migrations to make new migrations , that's why it was removed.  Now, we have new ones.

**Comment by Aymammet** [comment]
> i removed migrations to make new migrations , that's why it was removed. Now, we have new ones.



> i removed migrations to make new migrations , that's why it was removed. Now, we have new ones.
Whether you make or not, in each app you shoul leave __init__.py files. Event thet are empty they should stay there

image

**Comment by Aymammet** [comment]
> i removed migrations to make new migrations , that's why it was removed. Now, we have new ones.

Look at these responses :

**Comment by Aymammet** [comment]
> > i removed migrations to make new migrations , that's why it was removed. Now, we have new ones.
> 
> Look at these responses :

image

**Review by Aymammet — CHANGES_REQUESTED** [review]
All of your apps should have init.py file inside directory.

**Comment by anurmamedov** [comment]
all of them has 

image

**Comment by Aymammet** [comment]
> all of them has
> 
> image

image

**Comment by Aymammet** [comment]
image

**Comment by anurmamedov** [comment]
I see , but they are empty. there is nothing inside and wasn't anything. We will do more migrations and will be updated/upgraded.

**Comment by Aymammet** [comment]
> I see , but they are empty. there is nothing inside and wasn't anything. We will do more migrations and will be updated/upgraded.

They should stay in folder migrations. yours are different. Follow 'Files changed' pane to see differences

**Comment by anurmamedov** [comment]
just pushed it, included both files

**Review by Aymammet — APPROVED** [review]

**Pull request merged**
