### PR TITLE
SKY-08 : Add bootstrap

### PR DESCRIPTION
**Pull request by anurmamedov**
Downloaded bootstrap package from python. Created css and js folder in static. In both folders created bootstrap.css and bootstrap.js files.
Re-created collecstatic ,  added info in settings (static roots, app as bootstrap4 and improrted os).
Included footer (html) with inline css.

### CODE REVIEW

**Comment by Aymammet** [comment]
1. Use gitignore. Simply create gitignore file in project folder. Write the names of files we want to ignore. See example image below :

**Comment by anurmamedov** [comment]
2. image was deleted
3. no folder any more
4. updated to design of footer template

**Comment by Aymammet** [comment]
I still see __pycashe__ files. Use gitignore. Finish all steps I mentioned in previous comment

**Comment by anurmamedov** [comment]
updated pycache.

**Comment by Aymammet** [comment]
> updated pycache.

push your changes then

**Comment by anurmamedov** [comment]
keeps saying everything up to date, git push. 
I guess i have to make some other changes then it will work. Do changes in gitignore , still nothing

**Comment by anurmamedov** [comment]
maybe because current one is under review

**Pull request closed without merging**
